name: git_hub_update_telegram_bot
description: Telegram bot for GitHub developer's updates.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  path: ^1.8.0
  teledart: ^0.3.4
  http: ^0.13.5
  sqlite3: 1.7.0
  github: ^9.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
