name: git_hub_update_telegram_bot
description: Telegram bot for GitHub developer's updates.
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  path: ^1.8.0
  teledart: ^0.3.4
  http: ^0.13.5
  sqlite3: ^1.9.1
  github: ^9.4.0
  dartz: ^0.10.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
